# Generated by Django 3.0.7 on 2021-04-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210405_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='images',
            field=models.FileField(upload_to='images/blog/%Y/%m/%d', verbose_name='Images associées'),
        ),
        migrations.AlterField(
            model_name='postinfo',
            name='image_thumbnail',
            field=models.ImageField(blank=True, upload_to='images/blog/%Y/%m/%d', verbose_name='Photo Principale'),
        ),
    ]
