# Generated by Django 3.0.7 on 2021-04-06 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210405_1536'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubCateory',
            new_name='SubCategory',
        ),
    ]
