# Generated by Django 3.0.7 on 2021-04-07 07:20

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210406_1011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postinfo',
            options={'ordering': ('-show',), 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterField(
            model_name='postinfo',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='postinfo',
            name='subCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posts.SubCategory', verbose_name='Sous Catégorie'),
        ),
    ]
