# Generated by Django 3.0.7 on 2021-04-11 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=25, verbose_name='Téléphone')),
                ('subject', models.CharField(max_length=50, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('date_sent', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('treated', models.BooleanField(default=False, verbose_name='Traité')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ('-date_sent',),
            },
        ),
        migrations.CreateModel(
            name='SubScription_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Type Abonnement')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=25, verbose_name='Téléphone')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix Mensuel')),
                ('description', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('date_start', models.DateTimeField(auto_now_add=True, verbose_name='Date Début')),
                ('date_end', models.DateTimeField(auto_now_add=True, verbose_name='Date de Fin')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='contacts.SubScription_Category', verbose_name='Catégorie')),
            ],
        ),
    ]
