# Generated by Django 3.0.7 on 2021-04-11 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='price',
            new_name='actual_price',
        ),
        migrations.AddField(
            model_name='subscription_category',
            name='price',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=10, verbose_name='Prix Mensuel'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='category',
            field=models.ForeignKey(default='basic', on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='contacts.SubScription_Category', verbose_name='Catégorie'),
        ),
    ]
