# Generated by Django 3.0.7 on 2021-04-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20210411_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ('date_start',), 'verbose_name': 'Abonnement', 'verbose_name_plural': 'Abonnements'},
        ),
        migrations.AlterModelOptions(
            name='subscription_category',
            options={'ordering': ('-name',), 'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AddField(
            model_name='subscription',
            name='message',
            field=models.TextField(blank=True, verbose_name='Message'),
        ),
    ]
