# Generated by Django 3.0.7 on 2021-04-11 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20210411_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='actual_price',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='message',
        ),
    ]
