# Generated by Django 3.0.7 on 2021-04-13 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20210411_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=25, verbose_name='Téléphone')),
                ('description', models.TextField(verbose_name='Description')),
                ('date_start', models.DateTimeField(auto_now_add=True, verbose_name='Date Début')),
                ('date_end', models.DateTimeField(auto_now_add=True, verbose_name='Date de Fin')),
                ('category', models.ForeignKey(default='basic', on_delete=django.db.models.deletion.PROTECT, related_name='trials', to='contacts.SubScription_Category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Demande Démo',
                'verbose_name_plural': 'Demandes démo',
                'ordering': ('date_start',),
            },
        ),
    ]
