# Generated by Django 3.0.7 on 2021-05-02 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('-show',), 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
    ]
