# Generated by Django 3.0.7 on 2021-05-02 17:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20210502_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecontent',
            name='text',
            field=ckeditor.fields.RichTextField(default='text'),
        ),
    ]
