# Generated by Django 3.0.7 on 2021-05-03 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20210502_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon_url',
        ),
    ]
