# Generated by Django 3.0.7 on 2021-05-04 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20210504_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicecategory',
            old_name='icon_url',
            new_name='icon',
        ),
    ]
