# Generated by Django 3.0.7 on 2021-05-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20210504_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon_white',
            field=models.FileField(default='icon', upload_to='services', verbose_name='Icon Blanche'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(max_length=400, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.FileField(upload_to='services', verbose_name='Icon bleue'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='icon',
            field=models.ImageField(upload_to='service_categories', verbose_name='Icon'),
        ),
    ]
